# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /app

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /app

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /app/CMakeFiles /app//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /app/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named night_sky

# Build rule for target.
night_sky: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 night_sky
.PHONY : night_sky

# fast build rule for target.
night_sky/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/night_sky.dir/build.make CMakeFiles/night_sky.dir/build
.PHONY : night_sky/fast

catalog.o: catalog.c.o
.PHONY : catalog.o

# target to build an object file
catalog.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/night_sky.dir/build.make CMakeFiles/night_sky.dir/catalog.c.o
.PHONY : catalog.c.o

catalog.i: catalog.c.i
.PHONY : catalog.i

# target to preprocess a source file
catalog.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/night_sky.dir/build.make CMakeFiles/night_sky.dir/catalog.c.i
.PHONY : catalog.c.i

catalog.s: catalog.c.s
.PHONY : catalog.s

# target to generate assembly for a file
catalog.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/night_sky.dir/build.make CMakeFiles/night_sky.dir/catalog.c.s
.PHONY : catalog.c.s

elevation_view.o: elevation_view.c.o
.PHONY : elevation_view.o

# target to build an object file
elevation_view.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/night_sky.dir/build.make CMakeFiles/night_sky.dir/elevation_view.c.o
.PHONY : elevation_view.c.o

elevation_view.i: elevation_view.c.i
.PHONY : elevation_view.i

# target to preprocess a source file
elevation_view.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/night_sky.dir/build.make CMakeFiles/night_sky.dir/elevation_view.c.i
.PHONY : elevation_view.c.i

elevation_view.s: elevation_view.c.s
.PHONY : elevation_view.s

# target to generate assembly for a file
elevation_view.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/night_sky.dir/build.make CMakeFiles/night_sky.dir/elevation_view.c.s
.PHONY : elevation_view.c.s

main.o: main.c.o
.PHONY : main.o

# target to build an object file
main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/night_sky.dir/build.make CMakeFiles/night_sky.dir/main.c.o
.PHONY : main.c.o

main.i: main.c.i
.PHONY : main.i

# target to preprocess a source file
main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/night_sky.dir/build.make CMakeFiles/night_sky.dir/main.c.i
.PHONY : main.c.i

main.s: main.c.s
.PHONY : main.s

# target to generate assembly for a file
main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/night_sky.dir/build.make CMakeFiles/night_sky.dir/main.c.s
.PHONY : main.c.s

sky_model.o: sky_model.c.o
.PHONY : sky_model.o

# target to build an object file
sky_model.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/night_sky.dir/build.make CMakeFiles/night_sky.dir/sky_model.c.o
.PHONY : sky_model.c.o

sky_model.i: sky_model.c.i
.PHONY : sky_model.i

# target to preprocess a source file
sky_model.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/night_sky.dir/build.make CMakeFiles/night_sky.dir/sky_model.c.i
.PHONY : sky_model.c.i

sky_model.s: sky_model.c.s
.PHONY : sky_model.s

# target to generate assembly for a file
sky_model.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/night_sky.dir/build.make CMakeFiles/night_sky.dir/sky_model.c.s
.PHONY : sky_model.c.s

sky_view.o: sky_view.c.o
.PHONY : sky_view.o

# target to build an object file
sky_view.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/night_sky.dir/build.make CMakeFiles/night_sky.dir/sky_view.c.o
.PHONY : sky_view.c.o

sky_view.i: sky_view.c.i
.PHONY : sky_view.i

# target to preprocess a source file
sky_view.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/night_sky.dir/build.make CMakeFiles/night_sky.dir/sky_view.c.i
.PHONY : sky_view.c.i

sky_view.s: sky_view.c.s
.PHONY : sky_view.s

# target to generate assembly for a file
sky_view.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/night_sky.dir/build.make CMakeFiles/night_sky.dir/sky_view.c.s
.PHONY : sky_view.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... night_sky"
	@echo "... catalog.o"
	@echo "... catalog.i"
	@echo "... catalog.s"
	@echo "... elevation_view.o"
	@echo "... elevation_view.i"
	@echo "... elevation_view.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... sky_model.o"
	@echo "... sky_model.i"
	@echo "... sky_model.s"
	@echo "... sky_view.o"
	@echo "... sky_view.i"
	@echo "... sky_view.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system
